# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-advanced
PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Andrea Pesaresi <andreapesaresi82@gmail.com>
PKG_VERSION:=1.0.4
PKG_RELEASE:=1

LUCI_TITLE:=LuCI app to set-up WED EDCCA
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
